### ISSUE TITLE
在centos 无法启动rails程序 SystemExit in HomeController#index

### ISSUE THREAD

**Issue by yreme** [goofansu/wechat-starter#15]
在ubuntu 15 使用rails s 启动可以访问。但在centos 6 和 centos 7 ，运行 rails s
```bash
$ rails  s
=> Booting Puma
=> Rails 4.2.6 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[17775] Puma starting in cluster mode...
[17775] * Version 3.4.0 (ruby 2.2.3-p173), codename: Owl Bowl Brawl
[17775] * Min threads: 1, max threads: 6
[17775] * Environment: development
[17775] * Process workers: 2
[17775] * Preloading application
[17775] * Listening on tcp://localhost:3000
```
但无法在浏览器访问， 访问localhost:3000 后，显示的错误为`SystemExit in HomeController#index`
```ruby

  # to allow using wechat, wechat_oauth2 in controller and wechat_config_js in view
  wechat_api

  def index
  end
```
错误位置在 
```bash
app/controllers/home_controller.rb:6:in `<class:HomeController>'
app/controllers/home_controller.rb:1:in `<top (required)>'
```

> PS. 本人把 pg 数据库改成了 sqlit3,  同时 gem 也相应的增加了 sqlit3， 应该对这个问题不产生影响。

**请问如何解决这个问题？**

**Comment by Eric-Guo** [comment]
请贴一下完整的backtrace，可以通过修改backtrace_silencers.rb关闭

```
  # You can also remove all the silencers if you're trying to debug a problem that might stem from framework code.
  Rails.backtrace_cleaner.remove_silencers!
```

**Comment by yreme** [comment]
非常谢谢！ 
我尝试修改 `config/initializers/backtrace_silencers.rb`成
```
# Be sure to restart your server when you modify this file.

# You can add backtrace silencers for libraries that you're using but don't wish to see in your backtraces.
# Rails.backtrace_cleaner.add_silencer { |line| line =~ /my_noisy_library/ }

# You can also remove all the silencers if you're trying to debug a problem that might stem from framework code.
Rails.backtrace_cleaner.remove_silencers!
```
已经不出现上述错误。

**Comment by Eric-Guo** [comment]
这个修改并不能修正你的错误。。不过工作了就好。。
