### ISSUE TITLE
创建自定义菜单出错？

### ISSUE THREAD

**Issue by zixzixzix** [goofansu/wechat-starter#20]
```
tianshengdeiMac:wechat_starter tiansheng$ wechat menu_create config\wechat_menu.yml
(erb):2:in `<main>': uninitialized constant Figaro (NameError)
	from /Users/tiansheng/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /Users/tiansheng/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /Users/tiansheng/.rvm/gems/ruby-2.3.0/gems/wechat-0.7.16/lib/wechat/api_loader.rb:54:in `config_from_file'
	from /Users/tiansheng/.rvm/gems/ruby-2.3.0/gems/wechat-0.7.16/lib/wechat/api_loader.rb:33:in `loading_config!'
	from /Users/tiansheng/.rvm/gems/ruby-2.3.0/gems/wechat-0.7.16/lib/wechat/api_loader.rb:26:in `config'
	from /Users/tiansheng/.rvm/gems/ruby-2.3.0/gems/wechat-0.7.16/lib/wechat/api_loader.rb:4:in `with'
	from /Users/tiansheng/.rvm/gems/ruby-2.3.0/gems/wechat-0.7.16/bin/wechat:41:in `<class:App>'
	from /Users/tiansheng/.rvm/gems/ruby-2.3.0/gems/wechat-0.7.16/bin/wechat:18:in `<top (required)>'
	from /Users/tiansheng/.rvm/gems/ruby-2.3.0/bin/wechat:23:in `load'
	from /Users/tiansheng/.rvm/gems/ruby-2.3.0/bin/wechat:23:in `<main>'
	from /Users/tiansheng/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tiansheng/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by frankgu** [comment]
@Eric-Guo @goofansu  大神们求帮忙我也遇到了这个问题， 总感觉是一个很简单的问题， 但是网上找不到解决方法， 万分感谢

**Comment by Eric-Guo** [comment]
这个是Figaro，wx_pay和wechat集成的问题，我周末会抽时间调查一下，wechat需要在命令行方式下，支持Figaro，如果存在的话。。

**Comment by Eric-Guo** [comment]
另外有个有点关系的[issue](https://github.com/Eric-Guo/wechat/issues/94)，可以参考。。

**Comment by goofansu** [comment]
请参看 https://github.com/goofansu/wechat-starter#create-customized-menu
