### ISSUE TITLE
脱离Figaro，便于使用wechat的命令

### ISSUE THREAD

**Issue by goofansu** [goofansu/wechat-starter#22]
因为在`wechat.yml`中使用了`Figaro`，所以[wechat gem提供的命令行](https://github.com/Eric-Guo/wechat#command-line-mode)都不能使用，会报错：

```
(erb):2:in `<main>': uninitialized constant Figaro (NameError)
       	from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/erb.rb:863:in `eval'
       	from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/erb.rb:863:in `result'
       	from /app/vendor/bundle/ruby/2.2.0/gems/wechat-0.7.15/lib/wechat/api_loader.rb:54:in `config_from_file'
       	from /app/vendor/bundle/ruby/2.2.0/gems/wechat-0.7.15/lib/wechat/api_loader.rb:33:in `loading_config!'
       	from /app/vendor/bundle/ruby/2.2.0/gems/wechat-0.7.15/lib/wechat/api_loader.rb:26:in `config'
       	from /app/vendor/bundle/ruby/2.2.0/gems/wechat-0.7.15/lib/wechat/api_loader.rb:4:in `with'
       	from /app/vendor/bundle/ruby/2.2.0/gems/wechat-0.7.15/bin/wechat:41:in `<class:App>'
       	from /app/vendor/bundle/ruby/2.2.0/gems/wechat-0.7.15/bin/wechat:18:in `<top (required)>'
       	from /app/vendor/bundle/bin/wechat:16:in `load'
       	from /app/vendor/bundle/bin/wechat:16:in `<main>'
```

**Comment by Eric-Guo** [comment]
其实也可以在wechat gem的命令行模式里面加上Figaro的探测，如果有，就先Require。

**Comment by goofansu** [comment]
@Eric-Guo 好啊，方便的话加一下吧

**Comment by goofansu** [comment]
@Eric-Guo 有空加一下吗？

**Comment by Eric-Guo** [comment]
好的。。

**Comment by Eric-Guo** [comment]
0.8.0支持Figaro的探测了。

**Comment by Eric-Guo** [comment]
也许给你关比较合适，顺便帮我测一下，哇哈哈

**Comment by goofansu** [comment]
@Eric-Guo 多谢。不报错了，但是无法拿到用Figaro定义的值。

**Comment by Eric-Guo** [comment]
我试了application.yml.sample的，好像有作用啊，你可以改一个access_token的存储位置验证这一点。

**Comment by goofansu** [comment]
@Eric-Guo 知道问题了，下面这种样子不行

```
development:
    wechat_app_id: "wx90b3e204fcb50e72"
    wechat_secret: "7153c8b6f0c2f5e5b6672033422ae3fb"
```

**Comment by Eric-Guo** [comment]
这个就算了吧？关键wechat命令行没有Rails环境，也不知道是否是dev啊。。

**Comment by goofansu** [comment]
嗯，我感觉可以了，合并吧
